import esbuild from "esbuild";
import process from "process";
import fs from "fs/promises";
import path from "path";
import os from "os";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Optional: after each successful build, mirror the plugin outputs into a
// vault's plugin folder so Obsidian picks them up immediately. Set
// OBSIDIAN_PLUGIN_DIR to <Vault>/.obsidian/plugins/github-gitless-sync.
// data.json is intentionally not mirrored — that file is vault-specific
// state owned by Obsidian, not a build output.
//
// We expand a leading "~/" ourselves so the value works whether the env var
// is set inline in a shell (where the shell would expand it) or via an IDE
// run config (which passes it through literally — fs.mkdir would otherwise
// create a "~" folder under the project root).
function expandHome(p) {
  if (!p) return p;
  if (p === "~") return os.homedir();
  if (p.startsWith("~/")) return path.join(os.homedir(), p.slice(2));
  return p;
}
const mirrorTarget = expandHome(process.env.OBSIDIAN_PLUGIN_DIR);
const mirroredFiles = ["main.js", "manifest.json", "styles.css"];

const mirrorPlugin = {
  name: "mirror-to-vault",
  setup(build) {
    build.onEnd(async (result) => {
      if (!mirrorTarget) return;
      if (result.errors.length > 0) return;
      try {
        await fs.mkdir(mirrorTarget, { recursive: true });
        await Promise.all(
          mirroredFiles.map((file) =>
            fs.copyFile(file, path.join(mirrorTarget, file)),
          ),
        );
        console.log(`[mirror] copied to ${mirrorTarget}`);
      } catch (err) {
        console.error(`[mirror] failed: ${err.message}`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["./src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // `path` is intentionally NOT externalized: src/gi.ts imports
    // path-browserify (pure JS, mobile-safe) and esbuild needs to
    // bundle it rather than leave a top-level require("path") that
    // would crash on Obsidian Mobile.
    ...builtins.filter((m) => m !== "path"),
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [mirrorPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
